-- This file is auto-generated by install/install-cpc.sh, which compiles the
-- Eunoia signature recorded in install/defs/Cpc.cached.eo into Lean.
-- Do not edit. Change the signature, or the compiler, instead.
--
-- The SMT-LIB semantics and the checker specification that these definitions
-- realize are documented in docs/smt-model-definitions.pdf.

module

public import CpcMini.SmtEval
import all CpcMini.SmtEval

public section

set_option linter.unusedVariables false
set_option maxHeartbeats 10000000

namespace Eo

open SmtEval

/-
Ordinary user operators.
-/
inductive UserOp : Type where
  | Int : UserOp
  | Real : UserOp
  | BitVec : UserOp
  | Char : UserOp
  | Seq : UserOp
  | not : UserOp
  | and : UserOp
  | imp : UserOp
  | eq : UserOp

deriving Repr, DecidableEq, Inhabited, Ord

mutual

/- Term definition -/
inductive Term : Type where
  | UOp : UserOp -> Term
  | __eo_List : Term
  | __eo_List_nil : Term
  | __eo_List_cons : Term
  | Bool : Term
  | Boolean : native_Bool -> Term
  | Numeral : native_Int -> Term
  | Rational : native_Rat -> Term
  | String : native_String -> Term
  | Binary : native_Int -> native_Int -> Term
  | Type : Term
  | Stuck : Term
  | Apply : Term -> Term -> Term
  | FunType : Term
  | Var : Term -> Term -> Term
  | DatatypeType : native_String -> DatatypeDecl -> Term
  | DatatypeTypeRef : native_String -> Term
  | DtcAppType : Term -> Term -> Term
  | DtCons : native_String -> DatatypeDecl -> native_Nat -> Term
  | DtSel : native_String -> DatatypeDecl -> native_Nat -> native_Nat -> Term
  | USort : native_Nat -> Term
  | UConst : native_Nat -> Term -> Term

deriving Repr, DecidableEq, Inhabited, Ord

/-
Eunoia datatype declarations.
-/
inductive DatatypeDecl : Type where
  | nil : DatatypeDecl
  | cons : native_String -> Datatype -> DatatypeDecl -> DatatypeDecl
deriving Repr, DecidableEq, Inhabited, Ord

/-
Eunoia datatypes.
-/
inductive Datatype : Type where
  | null : Datatype
  | sum : DatatypeCons -> Datatype -> Datatype
deriving Repr, DecidableEq, Inhabited, Ord

/-
Eunoia datatype constructors.
-/
inductive DatatypeCons : Type where
  | unit : DatatypeCons
  | cons : Term -> DatatypeCons -> DatatypeCons
deriving Repr, DecidableEq, Inhabited, Ord

end

-- Equality and ordering of Eunoia terms, which the checker asks for and the
-- Term inductive above is what decides. They stand after the mutual block
-- rather than beside the inductive whose `deriving` makes them possible: a
-- mutual block holds inductives or definitions, never both.

/- Term equality -/
def native_teq : Term -> Term -> native_Bool
  | x, y => decide (x = y)

/- Term less than, based on arbitrary ordering -/
def native_tcmp (a b : Term) : native_Bool :=
  match compare a b with
  | Ordering.lt => true
  | _ => false

end Eo
