-- This file is auto-generated by install/install-cpc.sh, which compiles the
-- Eunoia signature recorded in install/defs/Cpc.cached.eo into Lean.
-- Do not edit. Change the signature, or the compiler, instead.
--
-- The SMT-LIB semantics and the checker specification that these definitions
-- realize are documented in docs/smt-model-definitions.pdf.

module

public import Init

public section

set_option linter.unusedVariables false

namespace SmtEval

instance : Ord Rat where
  compare a b :=
    -- compare a.num / a.den vs b.num / b.den by cross-multiplication
    compare (a.num * Int.ofNat b.den) (b.num * Int.ofNat a.den)

-- The primitive operations every other module is written over.
abbrev native_Bool := Bool

abbrev native_Int := Int

abbrev native_Rat := Rat

abbrev native_Nat := Nat

abbrev native_Char := Nat

abbrev native_String := List native_Char

def native_string_lit (s : String) : native_String :=
  s.toList.map Char.toNat

def native_ite {T : Type} (c : native_Bool) (t e : T) : T :=
  if c then t else e

def native_not : native_Bool -> native_Bool
  | x => Bool.not x

def native_and : native_Bool -> native_Bool -> native_Bool
  | x, y => x && y

def native_zeq : native_Int -> native_Int -> native_Bool
  | x, y => decide (x = y)

def native_mod_total : native_Int -> native_Int -> native_Int
  | x, y => x%y

def native_zexp_total (x : native_Int) (y : native_Int) : native_Int :=
  if y < 0 then 0 else (x ^ (Int.toNat y))

def native_int_pow2 (n : native_Int) : native_Int :=
  (native_zexp_total 2 n)

def native_mk_rational : native_Int -> native_Int -> native_Rat
  | x, y => x/y

def native_streq : native_String -> native_String -> native_Bool
  | x, y => decide (x = y)

syntax "native_nat_zero" : term
macro_rules
  | `(native_nat_zero) => `(Nat.zero)

syntax "native_nat_succ " term : term
macro_rules
  | `(native_nat_succ $x) => `(Nat.succ $x)

end SmtEval
