-- This file is auto-generated by install/install-cpc.sh, which compiles the
-- Eunoia signature recorded in install/defs/Cpc.cached.eo into Lean.
-- Do not edit. Change the signature, or the compiler, instead.
--
-- The SMT-LIB semantics and the checker specification that these definitions
-- realize are documented in docs/smt-model-definitions.pdf.

module

public import CpcMini.SmtModel
import all CpcMini.SmtModel
public import CpcMini.LogosTerm
import all CpcMini.LogosTerm

@[expose] public section

open SmtEval
open Eo
open Smtm

set_option linter.unusedVariables false
set_option maxHeartbeats 10000000


/-
Definitions for eo_to_smt_type, eo_to_smt
-/
noncomputable section

def __eo_to_smt_param : SmtDatatypeCons -> native_Nat -> SmtType
  | (SmtDatatypeCons.cons T ps), native_nat_zero => T
  | (SmtDatatypeCons.cons T ps), (native_nat_succ i) => (__eo_to_smt_param ps i)
  | ps, i => SmtType.None


def __eo_to_smt_reserved_datatype_name (s : native_String) : native_Bool :=
  (native_string_prefix_eq (native_string_lit "@") s)



mutual

def __eo_to_smt_type : Term -> SmtType
  | T => (__eo_to_smt_type_in SmtDatatypeCons.unit T)


def __eo_to_smt_args (ps : SmtDatatypeCons) : DatatypeArgs -> SmtDatatypeCons
  | DatatypeArgs.nil => SmtDatatypeCons.unit
  | (DatatypeArgs.cons T a) => (SmtDatatypeCons.cons (__eo_to_smt_type_in ps T) (__eo_to_smt_args ps a))


def __eo_to_smt_datatype_cons (ps : SmtDatatypeCons) : DatatypeCons -> SmtDatatypeCons
  | DatatypeCons.unit => SmtDatatypeCons.unit
  | (DatatypeCons.cons U c) => (SmtDatatypeCons.cons (__eo_to_smt_type_in ps U) (__eo_to_smt_datatype_cons ps c))


def __eo_to_smt_datatype (ps : SmtDatatypeCons) : Datatype -> SmtDatatype
  | (Datatype.sum c d) => (SmtDatatype.sum (__eo_to_smt_datatype_cons ps c) (__eo_to_smt_datatype ps d))
  | Datatype.null => SmtDatatype.null


def __eo_to_smt_datatype_decl_in (ps : SmtDatatypeCons) : DatatypeDecl -> SmtDatatypeDecl
  | (DatatypeDecl.cons s d dd) => (SmtDatatypeDecl.cons s (__eo_to_smt_datatype ps d) (__eo_to_smt_datatype_decl_in ps dd))
  | (DatatypeDecl.params a dd) => (__eo_to_smt_datatype_decl_in (__eo_to_smt_args ps a) dd)
  | DatatypeDecl.nil => SmtDatatypeDecl.nil


def __eo_to_smt_datatype_decl (dd : DatatypeDecl) : SmtDatatypeDecl :=
  (__eo_to_smt_datatype_decl_in SmtDatatypeCons.unit dd)

def __eo_to_smt_type_in (ps : SmtDatatypeCons) : Term -> SmtType
  | (Term.DtParam i) => (__eo_to_smt_param ps i)
  | Term.Bool => SmtType.Bool
  | (Term.DatatypeType s (DatatypeDecl.params a dd)) => (native_ite (__eo_to_smt_reserved_datatype_name s) SmtType.None (SmtType.Datatype s (__eo_to_smt_datatype_decl_in (__eo_to_smt_args ps a) dd)))
  | (Term.DatatypeType s dd) => (native_ite (__eo_to_smt_reserved_datatype_name s) SmtType.None (SmtType.Datatype s (__eo_to_smt_datatype_decl dd)))
  | (Term.DatatypeTypeRef s) => (native_ite (__eo_to_smt_reserved_datatype_name s) SmtType.None (SmtType.TypeRef s))
  | (Term.DtcAppType T1 T2) =>
    let _v0 := (__eo_to_smt_type_in ps T2)
    let _v1 := (__eo_to_smt_type_in ps T1)
    (__smtx_typeof_guard _v1 (__smtx_typeof_guard _v0 (SmtType.DtcAppType _v1 _v0)))
  | (Term.USort i) => (SmtType.USort i)
  | (Term.Apply (Term.Apply Term.FunType T1) T2) =>
    let _v0 := (__eo_to_smt_type_in ps T2)
    let _v1 := (__eo_to_smt_type_in ps T1)
    (__smtx_typeof_guard _v1 (__smtx_typeof_guard _v0 (SmtType.FunType _v1 _v0)))
  | (Term.UOp UserOp.Int) => SmtType.Int
  | (Term.UOp UserOp.Real) => SmtType.Real
  | (Term.Apply (Term.UOp UserOp.BitVec) (Term.Numeral x1)) => (native_ite (native_zleq 0 x1) (SmtType.BitVec (native_int_to_nat x1)) SmtType.None)
  | (Term.UOp UserOp.Char) => SmtType.Char
  | (Term.Apply (Term.UOp UserOp.Seq) x1) =>
    let _v0 := (__eo_to_smt_type_in ps x1)
    (__smtx_typeof_guard _v0 (SmtType.Seq _v0))
  | T => SmtType.None


def __eo_to_smt : Term -> SmtTerm
  | (Term.Boolean b) => (SmtTerm.Boolean b)
  | (Term.Numeral n) => (SmtTerm.Numeral n)
  | (Term.Rational r) => (SmtTerm.Rational r)
  | (Term.String s) => (SmtTerm.String s)
  | (Term.Binary w n) => (SmtTerm.Binary w n)
  | (Term.Var (Term.String s) T) => (SmtTerm.Var s (__eo_to_smt_type T))
  | (Term.DtCons s dd i) => (native_ite (__eo_to_smt_reserved_datatype_name s) SmtTerm.None (SmtTerm.DtCons s (__eo_to_smt_datatype_decl dd) i))
  | (Term.DtSel s dd i j) => (native_ite (__eo_to_smt_reserved_datatype_name s) SmtTerm.None (SmtTerm.DtSel s (__eo_to_smt_datatype_decl dd) i j))
  | (Term.UConst i T) => (SmtTerm.UConst (native_uconst_id i) (__eo_to_smt_type T))
  | (Term.Apply (Term.UOp UserOp.not) x1) => (SmtTerm.not (__eo_to_smt x1))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.and) x1) x2) => (SmtTerm.and (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.imp) x1) x2) => (SmtTerm.imp (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.eq) x1) x2) => (SmtTerm.eq (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply f y) => (SmtTerm.Apply (__eo_to_smt f) (__eo_to_smt y))
  | y => SmtTerm.None




end

end

/-
Eunoia satisfiability depends on SMT satisfiability.
-/
def eo_satisfiability (t : Term) (b : Bool) : Prop :=
  (smt_satisfiability (__eo_to_smt t) b)

/- ---------------------------------------------- -/
