-- This file is auto-generated by install/install-cpc.sh, which compiles the
-- Eunoia signature recorded in install/defs/Cpc.cached.eo into Lean.
-- Do not edit. Change the signature, or the compiler, instead.
--
-- The SMT-LIB semantics and the checker specification that these definitions
-- realize are documented in docs/smt-model-definitions.pdf.

module

public import Cpc.SmtModel
import all Cpc.SmtModel
public import Cpc.LogosTerm
import all Cpc.LogosTerm

@[expose] public section

open SmtEval
open Eo
open Smtm

set_option linter.unusedVariables false
set_option maxHeartbeats 10000000


/-
Definitions for eo_to_smt_type, eo_to_smt
-/
noncomputable section

def __eo_to_smt_array_deq_diff (a : SmtTerm) : SmtType -> SmtTerm -> SmtType -> SmtTerm
  | (SmtType.Map aT aU), b, (SmtType.Map bT bU) => (SmtTerm.map_diff a b)
  | aT, b, bT => SmtTerm.None


def __eo_to_smt_bv_size : SmtType -> native_Int
  | (SmtType.BitVec x1) => (native_nat_to_int x1)
  | t1 => (native_zneg 1)


def __eo_to_smt_seq_empty : SmtType -> SmtTerm
  | (SmtType.Seq T) => (SmtTerm.seq_empty T)
  | T => SmtTerm.None


def __eo_to_smt_nat_is_valid : Term -> native_Bool
  | (Term.Numeral n) => (native_zleq 0 n)
  | t => false


def __eo_to_smt_nat : Term -> native_Nat
  | (Term.Numeral n) => (native_int_to_nat n)
  | t => native_nat_zero


def __eo_to_smt_re_unfold_pos_component (s : SmtTerm) : SmtTerm -> native_Nat -> SmtTerm
  | (SmtTerm.re_concat r1 r2), native_nat_zero => (SmtTerm.str_substr s (SmtTerm.Numeral 0) (SmtTerm.str_indexof_re_split s r1 r2))
  | (SmtTerm.re_concat r1 r2), (native_nat_succ n) =>
    let _v0 := (SmtTerm.str_indexof_re_split s r1 r2)
    (__eo_to_smt_re_unfold_pos_component (SmtTerm.str_substr s _v0 (SmtTerm.neg (SmtTerm.str_len s) _v0)) r2 n)
  | _y2, _y3 => SmtTerm.None


def __eo_to_smt_tester : SmtTerm -> SmtTerm
  | (SmtTerm.DtCons s dd n) => (SmtTerm.DtTester s dd n)
  | t => SmtTerm.None


def __eo_to_smt_updater_rec : SmtTerm -> native_Nat -> SmtTerm -> SmtTerm -> SmtTerm -> SmtTerm
  | (SmtTerm.DtSel s dd n m), native_nat_zero, t, u, acc => acc
  | (SmtTerm.DtSel s dd n m), (native_nat_succ k), t, u, acc => (SmtTerm.Apply (__eo_to_smt_updater_rec (SmtTerm.DtSel s dd n m) k t u acc) (native_ite (native_nateq m k) u (SmtTerm.Apply (SmtTerm.DtSel s dd n k) t)))
  | v, k, t, u, acc => SmtTerm.None


def __eo_to_smt_updater : SmtTerm -> SmtTerm -> SmtTerm -> SmtTerm
  | (SmtTerm.DtSel s dd n m), t, u =>
    let _v0 := (__smtx_dt_num_sels (__smtx_dd_lookup s dd) n)
    (native_ite (native_zlt (native_nat_to_int m) (native_nat_to_int _v0)) (SmtTerm.ite (SmtTerm.Apply (SmtTerm.DtTester s dd n) t) (__eo_to_smt_updater_rec (SmtTerm.DtSel s dd n m) _v0 t u (SmtTerm.DtCons s dd n)) t) SmtTerm.None)
  | sel, t, u => SmtTerm.None


def __eo_to_smt_tuple_decl (d : SmtDatatype) : SmtDatatypeDecl :=
  (SmtDatatypeDecl.cons (native_string_lit "@Tuple") d SmtDatatypeDecl.nil)

def __eo_to_smt_tuple_prepend_rec (dd : SmtDatatypeDecl) (d : SmtDatatype) (tail : SmtTerm) : native_Nat -> SmtTerm -> SmtTerm
  | native_nat_zero, acc => acc
  | (native_nat_succ n), acc => (SmtTerm.Apply (__eo_to_smt_tuple_prepend_rec dd d tail n acc) (SmtTerm.Apply (SmtTerm.DtSel (native_string_lit "@Tuple") dd native_nat_zero n) tail))


def __eo_to_smt_tuple_select : SmtType -> SmtTerm -> SmtTerm -> SmtTerm
  | (SmtType.Datatype s (SmtDatatypeDecl.cons s2 d SmtDatatypeDecl.nil)), (SmtTerm.Numeral n), t => (native_ite (native_and (native_and (native_streq s (native_string_lit "@Tuple")) (native_streq s2 (native_string_lit "@Tuple"))) (native_zleq 0 n)) (SmtTerm.Apply (SmtTerm.DtSel (native_string_lit "@Tuple") (__eo_to_smt_tuple_decl d) native_nat_zero (native_int_to_nat n)) t) SmtTerm.None)
  | T, n, t => SmtTerm.None


def __eo_to_smt_tuple_update : SmtType -> SmtTerm -> SmtTerm -> SmtTerm -> SmtTerm
  | (SmtType.Datatype s (SmtDatatypeDecl.cons s2 d SmtDatatypeDecl.nil)), (SmtTerm.Numeral n), t, u => (native_ite (native_and (native_and (native_streq s (native_string_lit "@Tuple")) (native_streq s2 (native_string_lit "@Tuple"))) (native_zleq 0 n)) (__eo_to_smt_updater (SmtTerm.DtSel (native_string_lit "@Tuple") (__eo_to_smt_tuple_decl d) native_nat_zero (native_int_to_nat n)) t u) SmtTerm.None)
  | T, n, t, u => SmtTerm.None


def __eo_to_smt_set_empty : SmtType -> SmtTerm
  | (SmtType.Set T) => (SmtTerm.set_empty T)
  | T => SmtTerm.None


def __eo_to_smt_set_elem_type : SmtType -> SmtType
  | (SmtType.Set T) => T
  | T => SmtType.None


def __eo_to_smt_sets_deq_diff (a : SmtTerm) : SmtType -> SmtTerm -> SmtType -> SmtTerm
  | (SmtType.Set aT), b, (SmtType.Set bT) => (SmtTerm.map_diff a b)
  | aT, b, bT => SmtTerm.None


def __eo_to_smt_reserved_datatype_name (s : native_String) : native_Bool :=
  (native_string_prefix_eq (native_string_lit "@") s)



mutual

def __eo_to_smt_datatype_cons : DatatypeCons -> SmtDatatypeCons
  | DatatypeCons.unit => SmtDatatypeCons.unit
  | (DatatypeCons.cons U c) => (SmtDatatypeCons.cons (__eo_to_smt_type U) (__eo_to_smt_datatype_cons c))


def __eo_to_smt_datatype : Datatype -> SmtDatatype
  | (Datatype.sum c d) => (SmtDatatype.sum (__eo_to_smt_datatype_cons c) (__eo_to_smt_datatype d))
  | Datatype.null => SmtDatatype.null


def __eo_to_smt_datatype_decl : DatatypeDecl -> SmtDatatypeDecl
  | (DatatypeDecl.cons s d dd) => (SmtDatatypeDecl.cons s (__eo_to_smt_datatype d) (__eo_to_smt_datatype_decl dd))
  | DatatypeDecl.nil => SmtDatatypeDecl.nil


def __eo_to_smt_distinct_pairs (s : SmtTerm) : Term -> SmtTerm
  | (Term.Apply (Term.Apply (Term.UOp UserOp._at__at_TypedList_cons) x) xs) => (SmtTerm.and (SmtTerm.not (SmtTerm.eq s (__eo_to_smt x))) (__eo_to_smt_distinct_pairs s xs))
  | (Term.Apply (Term.UOp UserOp._at__at_TypedList_nil) T) => (SmtTerm.Boolean true)
  | xs => SmtTerm.None


def __eo_to_smt_distinct : Term -> SmtTerm
  | (Term.Apply (Term.Apply (Term.UOp UserOp._at__at_TypedList_cons) x) xs) => (SmtTerm.and (__eo_to_smt_distinct_pairs (__eo_to_smt x) xs) (__eo_to_smt_distinct xs))
  | (Term.Apply (Term.UOp UserOp._at__at_TypedList_nil) T) => (SmtTerm.Boolean true)
  | xs => SmtTerm.None


def __eo_to_smt_typed_list_elem_type : Term -> SmtType
  | (Term.Apply (Term.UOp UserOp._at__at_TypedList_nil) T) =>
    let _v0 := (__eo_to_smt_type T)
    (native_ite (__smtx_type_wf _v0) _v0 SmtType.None)
  | (Term.Apply (Term.Apply (Term.UOp UserOp._at__at_TypedList_cons) t) ts) =>
    let _v0 := (__smtx_typeof (__eo_to_smt t))
    (native_ite (native_Teq _v0 (__eo_to_smt_typed_list_elem_type ts)) _v0 SmtType.None)
  | t => SmtType.None


def __eo_to_smt_type_tuple (U : SmtType) : SmtType -> SmtType
  | (SmtType.Datatype s (SmtDatatypeDecl.cons s2 (SmtDatatype.sum c SmtDatatype.null) SmtDatatypeDecl.nil)) => (native_ite (native_and (native_and (native_streq s (native_string_lit "@Tuple")) (native_streq s2 (native_string_lit "@Tuple"))) (__smtx_type_wf_component U)) (SmtType.Datatype (native_string_lit "@Tuple") (__eo_to_smt_tuple_decl (SmtDatatype.sum (SmtDatatypeCons.cons U c) SmtDatatype.null))) SmtType.None)
  | T => SmtType.None


def __eo_to_smt_tuple_prepend_of_type : SmtType -> SmtTerm -> SmtType -> SmtTerm -> SmtTerm
  | (SmtType.Datatype s (SmtDatatypeDecl.cons s2 (SmtDatatype.sum c SmtDatatype.null) SmtDatatypeDecl.nil)), h, hT, tail =>
    let _v1 := (__eo_to_smt_tuple_decl (SmtDatatype.sum (SmtDatatypeCons.cons hT c) SmtDatatype.null))
    let _v3 := (SmtDatatype.sum c SmtDatatype.null)
    (native_ite (native_and (native_and (native_streq s (native_string_lit "@Tuple")) (native_streq s2 (native_string_lit "@Tuple"))) (__smtx_type_wf (SmtType.Datatype (native_string_lit "@Tuple") _v1))) (__eo_to_smt_tuple_prepend_rec (__eo_to_smt_tuple_decl _v3) _v3 tail (__smtx_dt_num_sels _v3 native_nat_zero) (SmtTerm.Apply (SmtTerm.DtCons (native_string_lit "@Tuple") _v1 native_nat_zero) h)) SmtTerm.None)
  | T, h, hT, tail => SmtTerm.None


def __eo_to_smt_tuple_prepend (h : SmtTerm) (hT : SmtType) (tail : SmtTerm) : SmtTerm :=
  (__eo_to_smt_tuple_prepend_of_type (__smtx_typeof tail) h hT tail)

def __eo_to_smt_set_insert : Term -> SmtTerm -> SmtTerm
  | (Term.Apply (Term.Apply (Term.UOp UserOp._at__at_TypedList_cons) t1) t2), t3 => (SmtTerm.set_union (SmtTerm.set_singleton (__eo_to_smt t1)) (__eo_to_smt_set_insert t2 t3))
  | (Term.Apply (Term.UOp UserOp._at__at_TypedList_nil) T), t3 => (native_ite (native_Teq (__smtx_typeof t3) (SmtType.Set (__eo_to_smt_type T))) t3 SmtTerm.None)
  | t2, t3 => SmtTerm.None


def __eo_to_smt_exists : Term -> SmtTerm -> SmtTerm
  | Term.__eo_List_nil, F => F
  | (Term.Apply (Term.Apply Term.__eo_List_cons (Term.Var (Term.String s) T)) vs), F => (SmtTerm.exists s (__eo_to_smt_type T) (__eo_to_smt_exists vs F))
  | vs, F => SmtTerm.None


def __eo_to_smt_quantifiers_skolemize : Term -> SmtTerm -> native_Nat -> SmtTerm
  | (Term.Apply (Term.Apply Term.__eo_List_cons (Term.Var (Term.String s) T)) vs), G, native_nat_zero => (SmtTerm.choice s (__eo_to_smt_type T) (__eo_to_smt_exists vs G))
  | (Term.Apply (Term.Apply Term.__eo_List_cons (Term.Var (Term.String s) T)) vs), G, (native_nat_succ n) =>
    let _v0 := (__eo_to_smt_type T)
    (__eo_to_smt_quantifiers_skolemize vs (SmtTerm.bind s _v0 (SmtTerm.choice s _v0 (__eo_to_smt_exists vs G)) G) n)
  | vs, G, t => SmtTerm.None


def __eo_to_smt_type : Term -> SmtType
  | Term.Bool => SmtType.Bool
  | (Term.DatatypeType s dd) => (native_ite (__eo_to_smt_reserved_datatype_name s) SmtType.None (SmtType.Datatype s (__eo_to_smt_datatype_decl dd)))
  | (Term.DatatypeTypeRef s) => (native_ite (__eo_to_smt_reserved_datatype_name s) SmtType.None (SmtType.TypeRef s))
  | (Term.DtcAppType T1 T2) =>
    let _v0 := (__eo_to_smt_type T2)
    let _v1 := (__eo_to_smt_type T1)
    (__smtx_typeof_guard _v1 (__smtx_typeof_guard _v0 (SmtType.DtcAppType _v1 _v0)))
  | (Term.USort i) => (SmtType.USort i)
  | (Term.Apply (Term.Apply Term.FunType T1) T2) =>
    let _v0 := (__eo_to_smt_type T2)
    let _v1 := (__eo_to_smt_type T1)
    (__smtx_typeof_guard _v1 (__smtx_typeof_guard _v0 (SmtType.FunType _v1 _v0)))
  | (Term.UOp UserOp.Int) => SmtType.Int
  | (Term.UOp UserOp.Real) => SmtType.Real
  | (Term.Apply (Term.UOp UserOp.BitVec) (Term.Numeral x1)) => (native_ite (native_zleq 0 x1) (SmtType.BitVec (native_int_to_nat x1)) SmtType.None)
  | (Term.UOp UserOp.Char) => SmtType.Char
  | (Term.Apply (Term.UOp UserOp.Seq) x1) =>
    let _v0 := (__eo_to_smt_type x1)
    (__smtx_typeof_guard _v0 (SmtType.Seq _v0))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.Array) x1) x2) =>
    let _v0 := (__eo_to_smt_type x2)
    let _v1 := (__eo_to_smt_type x1)
    (__smtx_typeof_guard _v1 (__smtx_typeof_guard _v0 (SmtType.Map _v1 _v0)))
  | (Term.UOp UserOp.RegLan) => SmtType.RegLan
  | (Term.UOp UserOp.UnitTuple) => (SmtType.Datatype (native_string_lit "@Tuple") (SmtDatatypeDecl.cons (native_string_lit "@Tuple") (SmtDatatype.sum SmtDatatypeCons.unit SmtDatatype.null) SmtDatatypeDecl.nil))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.Tuple) x1) x2) =>
    let _v0 := (__eo_to_smt_type_tuple (__eo_to_smt_type x1) (__eo_to_smt_type x2))
    (native_ite (__smtx_type_wf _v0) _v0 SmtType.None)
  | (Term.Apply (Term.UOp UserOp.Set) x1) =>
    let _v0 := (__eo_to_smt_type x1)
    (__smtx_typeof_guard _v0 (SmtType.Set _v0))
  | T => SmtType.None


def __eo_to_smt : Term -> SmtTerm
  | (Term.Boolean b) => (SmtTerm.Boolean b)
  | (Term.Numeral n) => (SmtTerm.Numeral n)
  | (Term.Rational r) => (SmtTerm.Rational r)
  | (Term.String s) => (SmtTerm.String s)
  | (Term.Binary w n) => (SmtTerm.Binary w n)
  | (Term.Var (Term.String s) T) => (SmtTerm.Var s (__eo_to_smt_type T))
  | (Term.DtCons s dd i) => (native_ite (__eo_to_smt_reserved_datatype_name s) SmtTerm.None (SmtTerm.DtCons s (__eo_to_smt_datatype_decl dd) i))
  | (Term.DtSel s dd i j) => (native_ite (__eo_to_smt_reserved_datatype_name s) SmtTerm.None (SmtTerm.DtSel s (__eo_to_smt_datatype_decl dd) i j))
  | (Term.UConst i T) => (SmtTerm.UConst (native_uconst_id i) (__eo_to_smt_type T))
  | (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp.ite) x1) x2) x3) => (SmtTerm.ite (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.UOp UserOp.not) x1) => (SmtTerm.not (__eo_to_smt x1))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.or) x1) x2) => (SmtTerm.or (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.and) x1) x2) => (SmtTerm.and (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.imp) x1) x2) => (SmtTerm.imp (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.xor) x1) x2) => (SmtTerm.xor (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.eq) x1) x2) => (SmtTerm.eq (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp UserOp.distinct) x1) => (native_ite (native_Teq (__eo_to_smt_typed_list_elem_type x1) SmtType.None) SmtTerm.None (__eo_to_smt_distinct x1))
  | (Term.Apply (Term.UOp UserOp._at_purify) x1) => (SmtTerm._at_purify (__eo_to_smt x1))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.plus) x1) x2) => (SmtTerm.plus (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.neg) x1) x2) => (SmtTerm.neg (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.mult) x1) x2) => (SmtTerm.mult (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.lt) x1) x2) => (SmtTerm.lt (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.leq) x1) x2) => (SmtTerm.leq (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.gt) x1) x2) => (SmtTerm.gt (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.geq) x1) x2) => (SmtTerm.geq (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp UserOp.to_real) x1) => (SmtTerm.to_real (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.to_int) x1) => (SmtTerm.to_int (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.is_int) x1) => (SmtTerm.is_int (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.abs) x1) => (SmtTerm.abs (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.__eoo_neg_2) x1) => (SmtTerm.uneg (__eo_to_smt x1))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.div) x1) x2) => (SmtTerm.div (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.mod) x1) x2) => (SmtTerm.mod (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.divisible) x1) x2) => (SmtTerm.divisible (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp UserOp.int_pow2) x1) => (SmtTerm.int_pow2 (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.int_log2) x1) => (SmtTerm.int_log2 (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.int_ispow2) x1) =>
    let _v0 := (__eo_to_smt x1)
    (SmtTerm.and (SmtTerm.geq _v0 (SmtTerm.Numeral 0)) (SmtTerm.eq _v0 (SmtTerm.int_pow2 (SmtTerm.int_log2 _v0))))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.div_total) x1) x2) => (SmtTerm.div_total (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.mod_total) x1) x2) => (SmtTerm.mod_total (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp UserOp._at_int_div_by_zero) x1) => (SmtTerm.div (__eo_to_smt x1) (SmtTerm.Numeral 0))
  | (Term.Apply (Term.UOp UserOp._at_mod_by_zero) x1) => (SmtTerm.mod (__eo_to_smt x1) (SmtTerm.Numeral 0))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.select) x1) x2) => (SmtTerm.select (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp.store) x1) x2) x3) => (SmtTerm.store (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.Apply (Term.UOp UserOp._at_array_deq_diff) x1) x2) =>
    let _v0 := (__eo_to_smt x2)
    let _v1 := (__eo_to_smt x1)
    (__eo_to_smt_array_deq_diff _v1 (__smtx_typeof _v1) _v0 (__smtx_typeof _v0))
  | (Term.Apply (Term.UOp UserOp._at_bvsize) x1) =>
    let _v0 := (__eo_to_smt_bv_size (__smtx_typeof (__eo_to_smt x1)))
    (native_ite (native_zleq 0 _v0) (SmtTerm._at_purify (SmtTerm.Numeral _v0)) SmtTerm.None)
  | (Term.Apply (Term.Apply (Term.UOp UserOp.concat) x1) x2) => (SmtTerm.concat (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp2 UserOp2.extract x1 x2) x3) => (SmtTerm.extract (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.UOp1 UserOp1.repeat x1) x2) => (SmtTerm.repeat (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp UserOp.bvnot) x1) => (SmtTerm.bvnot (__eo_to_smt x1))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvand) x1) x2) => (SmtTerm.bvand (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvor) x1) x2) => (SmtTerm.bvor (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvnand) x1) x2) => (SmtTerm.bvnand (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvnor) x1) x2) => (SmtTerm.bvnor (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvxor) x1) x2) => (SmtTerm.bvxor (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvxnor) x1) x2) => (SmtTerm.bvxnor (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvcomp) x1) x2) => (SmtTerm.bvcomp (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp UserOp.bvneg) x1) => (SmtTerm.bvneg (__eo_to_smt x1))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvadd) x1) x2) => (SmtTerm.bvadd (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvmul) x1) x2) => (SmtTerm.bvmul (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvudiv) x1) x2) => (SmtTerm.bvudiv (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvurem) x1) x2) => (SmtTerm.bvurem (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvsub) x1) x2) => (SmtTerm.bvsub (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvsdiv) x1) x2) => (SmtTerm.bvsdiv (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvsrem) x1) x2) => (SmtTerm.bvsrem (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvsmod) x1) x2) => (SmtTerm.bvsmod (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvult) x1) x2) => (SmtTerm.bvult (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvule) x1) x2) => (SmtTerm.bvule (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvugt) x1) x2) => (SmtTerm.bvugt (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvuge) x1) x2) => (SmtTerm.bvuge (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvslt) x1) x2) => (SmtTerm.bvslt (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvsle) x1) x2) => (SmtTerm.bvsle (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvsgt) x1) x2) => (SmtTerm.bvsgt (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvsge) x1) x2) => (SmtTerm.bvsge (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvshl) x1) x2) => (SmtTerm.bvshl (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvlshr) x1) x2) => (SmtTerm.bvlshr (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvashr) x1) x2) => (SmtTerm.bvashr (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp1 UserOp1.zero_extend x1) x2) => (SmtTerm.zero_extend (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp1 UserOp1.sign_extend x1) x2) => (SmtTerm.sign_extend (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp1 UserOp1.rotate_left x1) x2) => (SmtTerm.rotate_left (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp1 UserOp1.rotate_right x1) x2) => (SmtTerm.rotate_right (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp.bvite) x1) x2) x3) => (SmtTerm.ite (SmtTerm.eq (__eo_to_smt x1) (SmtTerm.Binary 1 1)) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvuaddo) x1) x2) => (SmtTerm.bvuaddo (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp UserOp.bvnego) x1) => (SmtTerm.bvnego (__eo_to_smt x1))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvsaddo) x1) x2) => (SmtTerm.bvsaddo (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvumulo) x1) x2) => (SmtTerm.bvumulo (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvsmulo) x1) x2) => (SmtTerm.bvsmulo (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvusubo) x1) x2) => (SmtTerm.bvusubo (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvssubo) x1) x2) => (SmtTerm.bvssubo (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvsdivo) x1) x2) => (SmtTerm.bvsdivo (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvultbv) x1) x2) => (SmtTerm.ite (SmtTerm.bvult (__eo_to_smt x1) (__eo_to_smt x2)) (SmtTerm.Binary 1 1) (SmtTerm.Binary 1 0))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.bvsltbv) x1) x2) => (SmtTerm.ite (SmtTerm.bvslt (__eo_to_smt x1) (__eo_to_smt x2)) (SmtTerm.Binary 1 1) (SmtTerm.Binary 1 0))
  | (Term.Apply (Term.UOp UserOp.bvredand) x1) =>
    let _v0 := (__eo_to_smt x1)
    (SmtTerm.bvcomp _v0 (SmtTerm.bvnot (SmtTerm.Binary (__eo_to_smt_bv_size (__smtx_typeof _v0)) 0)))
  | (Term.Apply (Term.UOp UserOp.bvredor) x1) =>
    let _v0 := (__eo_to_smt x1)
    (SmtTerm.bvnot (SmtTerm.bvcomp _v0 (SmtTerm.Binary (__eo_to_smt_bv_size (__smtx_typeof _v0)) 0)))
  | (Term.Apply (Term.UOp1 UserOp1._at_bit x1) x2) =>
    let _v1 := (__eo_to_smt x1)
    (SmtTerm.eq (SmtTerm.extract _v1 _v1 (__eo_to_smt x2)) (SmtTerm.Binary 1 1))
  | (Term.Apply (Term.Apply (Term.UOp UserOp._at_from_bools) x1) x2) => (SmtTerm.concat (__eo_to_smt x2) (SmtTerm.ite (__eo_to_smt x1) (SmtTerm.Binary 1 1) (SmtTerm.Binary 1 0)))
  | (Term.UOp1 UserOp1.seq_empty x1) => (__eo_to_smt_seq_empty (__eo_to_smt_type x1))
  | (Term.Apply (Term.UOp UserOp.str_len) x1) => (SmtTerm.str_len (__eo_to_smt x1))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.str_concat) x1) x2) => (SmtTerm.str_concat (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp.str_substr) x1) x2) x3) => (SmtTerm.str_substr (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.str_contains) x1) x2) => (SmtTerm.str_contains (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp.str_replace) x1) x2) x3) => (SmtTerm.str_replace (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp.str_indexof) x1) x2) x3) => (SmtTerm.str_indexof (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.str_at) x1) x2) => (SmtTerm.str_at (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.str_prefixof) x1) x2) => (SmtTerm.str_prefixof (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.str_suffixof) x1) x2) => (SmtTerm.str_suffixof (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp UserOp.str_rev) x1) => (SmtTerm.str_rev (__eo_to_smt x1))
  | (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp.str_update) x1) x2) x3) => (SmtTerm.str_update (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.UOp UserOp.str_to_lower) x1) => (SmtTerm.str_to_lower (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.str_to_upper) x1) => (SmtTerm.str_to_upper (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.str_to_code) x1) => (SmtTerm.str_to_code (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.str_from_code) x1) => (SmtTerm.str_from_code (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.str_is_digit) x1) => (SmtTerm.str_is_digit (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.str_to_int) x1) => (SmtTerm.str_to_int (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.str_from_int) x1) => (SmtTerm.str_from_int (__eo_to_smt x1))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.str_lt) x1) x2) => (SmtTerm.str_lt (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.str_leq) x1) x2) => (SmtTerm.str_leq (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp.str_replace_all) x1) x2) x3) => (SmtTerm.str_replace_all (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp.str_replace_re) x1) x2) x3) => (SmtTerm.str_replace_re (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp.str_replace_re_all) x1) x2) x3) => (SmtTerm.str_replace_re_all (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp.str_indexof_re) x1) x2) x3) => (SmtTerm.str_indexof_re (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.UOp UserOp.re_allchar) => SmtTerm.re_allchar
  | (Term.UOp UserOp.re_none) => SmtTerm.re_none
  | (Term.UOp UserOp.re_all) => SmtTerm.re_all
  | (Term.Apply (Term.UOp UserOp.str_to_re) x1) => (SmtTerm.str_to_re (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.re_mult) x1) => (SmtTerm.re_mult (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.re_plus) x1) => (SmtTerm.re_plus (__eo_to_smt x1))
  | (Term.Apply (Term.UOp1 UserOp1.re_exp x1) x2) => (SmtTerm.re_exp (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp UserOp.re_opt) x1) => (SmtTerm.re_opt (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.re_comp) x1) => (SmtTerm.re_comp (__eo_to_smt x1))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.re_range) x1) x2) => (SmtTerm.re_range (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.re_concat) x1) x2) => (SmtTerm.re_concat (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.re_inter) x1) x2) => (SmtTerm.re_inter (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.re_union) x1) x2) => (SmtTerm.re_union (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.re_diff) x1) x2) => (SmtTerm.re_diff (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp2 UserOp2.re_loop x1 x2) x3) => (SmtTerm.re_loop (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.str_in_re) x1) x2) => (SmtTerm.str_in_re (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp UserOp.seq_unit) x1) => (SmtTerm.seq_unit (__eo_to_smt x1))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.seq_nth) x1) x2) => (SmtTerm.seq_nth (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.UOp3 UserOp3._at_re_unfold_pos_component x1 x2 x3) => (native_ite (__eo_to_smt_nat_is_valid x3) (__eo_to_smt_re_unfold_pos_component (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt_nat x3)) SmtTerm.None)
  | (Term.Apply (Term.Apply (Term.UOp UserOp._at_strings_deq_diff) x1) x2) => (SmtTerm.seq_diff (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp._at_strings_stoi_result) x1) x2) =>
    let _v0 := (__eo_to_smt x2)
    let _v1 := (SmtTerm.Numeral 0)
    (SmtTerm.ite (SmtTerm.eq _v0 _v1) _v1 (SmtTerm.str_to_int (SmtTerm.str_substr (__eo_to_smt x1) _v1 _v0)))
  | (Term.Apply (Term.UOp UserOp._at_strings_stoi_non_digit) x1) => (SmtTerm.str_indexof_re (__eo_to_smt x1) (SmtTerm.re_inter SmtTerm.re_allchar (SmtTerm.re_comp (SmtTerm.re_range (SmtTerm.String (native_string_lit "0")) (SmtTerm.String (native_string_lit "9"))))) (SmtTerm.Numeral 0))
  | (Term.Apply (Term.Apply (Term.UOp UserOp._at_strings_itos_result) x1) x2) =>
    let _v0 := (__eo_to_smt x2)
    let _v1 := (SmtTerm.Numeral 0)
    (SmtTerm.ite (SmtTerm.eq _v0 _v1) _v1 (SmtTerm.str_to_int (SmtTerm.str_substr (SmtTerm.str_from_int (__eo_to_smt x1)) _v1 _v0)))
  | (Term.Apply (Term.Apply (Term.UOp UserOp._at_strings_num_occur) x1) x2) =>
    let _v0 := (SmtTerm.Numeral 0)
    let _v1 := (__eo_to_smt x1)
    let _v2 := (__eo_to_smt x2)
    (SmtTerm.neg (SmtTerm.str_len (SmtTerm.str_replace_all _v1 _v2 (SmtTerm.str_substr _v1 _v0 (SmtTerm.Numeral 1)))) (SmtTerm.str_len (SmtTerm.str_replace_all _v1 _v2 (SmtTerm.str_substr _v1 _v0 _v0))))
  | (Term.Apply (Term.Apply (Term.UOp UserOp._at_strings_num_occur_re) x1) x2) =>
    let _v0 := (SmtTerm.Numeral 0)
    let _v1 := (__eo_to_smt x1)
    let _v2 := (__eo_to_smt x2)
    (SmtTerm.neg (SmtTerm.str_len (SmtTerm.str_replace_re_all _v1 _v2 (SmtTerm.str_substr _v1 _v0 (SmtTerm.Numeral 1)))) (SmtTerm.str_len (SmtTerm.str_replace_re_all _v1 _v2 (SmtTerm.str_substr _v1 _v0 _v0))))
  | (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp._at_strings_occur_index) x1) x2) x3) => (SmtTerm._at_strings_occur_index (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp._at_strings_occur_index_re) x1) x2) x3) => (SmtTerm._at_strings_occur_index_re (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.Apply (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp._at_strings_replace_all_result) x1) x2) x3) x4) =>
    let _v0 := (__eo_to_smt x2)
    let _v1 := (__eo_to_smt x1)
    (SmtTerm.str_replace_all (SmtTerm.str_substr _v1 (SmtTerm._at_strings_occur_index _v1 _v0 (__eo_to_smt x4)) (SmtTerm.str_len _v1)) _v0 (__eo_to_smt x3))
  | (Term.Apply (Term.Apply (Term.Apply (Term.Apply (Term.UOp UserOp._at_strings_replace_re_all_result) x1) x2) x3) x4) =>
    let _v0 := (__eo_to_smt x2)
    let _v1 := (__eo_to_smt x1)
    (SmtTerm.str_replace_re_all (SmtTerm.str_substr _v1 (SmtTerm._at_strings_occur_index_re _v1 _v0 (__eo_to_smt x4)) (SmtTerm.str_len _v1)) _v0 (__eo_to_smt x3))
  | (Term.UOp3 UserOp3._at_witness_string_length x1 x2 x3) =>
    let _v0 := (__eo_to_smt_type x1)
    (native_ite (__eo_to_smt_nat_is_valid x2) (native_ite (__eo_to_smt_nat_is_valid x3) (SmtTerm.choice (native_string_lit "@x") _v0 (SmtTerm.eq (SmtTerm.str_len (SmtTerm.Var (native_string_lit "@x") _v0)) (__eo_to_smt x2))) SmtTerm.None) SmtTerm.None)
  | (Term.Apply (Term.UOp1 UserOp1.is x1) x2) => (SmtTerm.Apply (__eo_to_smt_tester (__eo_to_smt x1)) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp1 UserOp1.update x1) x2) x3) => (__eo_to_smt_updater (__eo_to_smt x1) (__eo_to_smt x2) (__eo_to_smt x3))
  | (Term.UOp UserOp.tuple_unit) => (SmtTerm.DtCons (native_string_lit "@Tuple") (SmtDatatypeDecl.cons (native_string_lit "@Tuple") (SmtDatatype.sum SmtDatatypeCons.unit SmtDatatype.null) SmtDatatypeDecl.nil) native_nat_zero)
  | (Term.Apply (Term.Apply (Term.UOp UserOp.tuple) x1) x2) =>
    let _v0 := (__eo_to_smt x1)
    (__eo_to_smt_tuple_prepend _v0 (__smtx_typeof _v0) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp1 UserOp1.tuple_select x1) x2) =>
    let _v0 := (__eo_to_smt x2)
    (__eo_to_smt_tuple_select (__smtx_typeof _v0) (__eo_to_smt x1) _v0)
  | (Term.Apply (Term.Apply (Term.UOp1 UserOp1.tuple_update x1) x2) x3) =>
    let _v0 := (__eo_to_smt x2)
    (__eo_to_smt_tuple_update (__smtx_typeof _v0) (__eo_to_smt x1) _v0 (__eo_to_smt x3))
  | (Term.UOp1 UserOp1.set_empty x1) => (__eo_to_smt_set_empty (__eo_to_smt_type x1))
  | (Term.Apply (Term.UOp UserOp.set_singleton) x1) => (SmtTerm.set_singleton (__eo_to_smt x1))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.set_union) x1) x2) => (SmtTerm.set_union (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.set_inter) x1) x2) => (SmtTerm.set_inter (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.set_minus) x1) x2) => (SmtTerm.set_minus (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.set_member) x1) x2) => (SmtTerm.set_member (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.set_subset) x1) x2) => (SmtTerm.set_subset (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp UserOp.set_choose) x1) =>
    let _v0 := (__eo_to_smt x1)
    (SmtTerm.map_diff _v0 (SmtTerm.set_empty (__eo_to_smt_set_elem_type (__smtx_typeof _v0))))
  | (Term.Apply (Term.UOp UserOp.set_is_empty) x1) =>
    let _v0 := (__eo_to_smt x1)
    (SmtTerm.eq _v0 (SmtTerm.set_empty (__eo_to_smt_set_elem_type (__smtx_typeof _v0))))
  | (Term.Apply (Term.UOp UserOp.set_is_singleton) x1) =>
    let _v0 := (__eo_to_smt x1)
    (SmtTerm.eq _v0 (SmtTerm.set_singleton (SmtTerm.map_diff _v0 (SmtTerm.set_empty (__eo_to_smt_set_elem_type (__smtx_typeof _v0))))))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.set_insert) x1) x2) => (__eo_to_smt_set_insert x1 (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp._at_sets_deq_diff) x1) x2) =>
    let _v0 := (__eo_to_smt x2)
    let _v1 := (__eo_to_smt x1)
    (__eo_to_smt_sets_deq_diff _v1 (__smtx_typeof _v1) _v0 (__smtx_typeof _v0))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.qdiv) x1) x2) => (SmtTerm.qdiv (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.qdiv_total) x1) x2) => (SmtTerm.qdiv_total (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp UserOp._at_div_by_zero) x1) => (SmtTerm.qdiv (__eo_to_smt x1) (SmtTerm.Rational (native_mk_rational 0 1)))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.forall) Term.__eo_List_nil) x1) => SmtTerm.None
  | (Term.Apply (Term.Apply (Term.UOp UserOp.forall) x1) x2) => (SmtTerm.not (__eo_to_smt_exists x1 (SmtTerm.not (__eo_to_smt x2))))
  | (Term.Apply (Term.Apply (Term.UOp UserOp.exists) Term.__eo_List_nil) x1) => SmtTerm.None
  | (Term.Apply (Term.Apply (Term.UOp UserOp.exists) x1) x2) => (__eo_to_smt_exists x1 (__eo_to_smt x2))
  | (Term.UOp2 UserOp2._at_quantifiers_skolemize (Term.Apply (Term.Apply (Term.UOp UserOp.forall) x1) x2) x3) => (native_ite (__eo_to_smt_nat_is_valid x3) (__eo_to_smt_quantifiers_skolemize x1 (SmtTerm.not (__eo_to_smt x2)) (__eo_to_smt_nat x3)) SmtTerm.None)
  | (Term.Apply (Term.UOp1 UserOp1.int_to_bv x1) x2) => (SmtTerm.int_to_bv (__eo_to_smt x1) (__eo_to_smt x2))
  | (Term.Apply (Term.UOp UserOp.ubv_to_int) x1) => (SmtTerm.ubv_to_int (__eo_to_smt x1))
  | (Term.Apply (Term.UOp UserOp.sbv_to_int) x1) => (SmtTerm.sbv_to_int (__eo_to_smt x1))
  | (Term.UOp2 UserOp2._at_const x1 x2) => (native_ite (__eo_to_smt_nat_is_valid x1) (SmtTerm.UConst (native_const_id (__eo_to_smt_nat x1)) (__eo_to_smt_type x2)) SmtTerm.None)
  | (Term.Apply f y) => (SmtTerm.Apply (__eo_to_smt f) (__eo_to_smt y))
  | y => SmtTerm.None




end

end

/-
Eunoia satisfiability depends on SMT satisfiability.
-/
def eo_satisfiability (t : Term) (b : Bool) : Prop :=
  (smt_satisfiability (__eo_to_smt t) b)

/- ---------------------------------------------- -/
