import Cpc.Native
open Eo
def t1 := (Term.Var (Term.String (SmtEval.native_string_lit "x")) (Term.UOp UserOp.Int))
def t2 := (Term.Apply Term.FunType (Term.UOp UserOp.Int))
def t3 := (Term.Apply t2 Term.Bool)
def t4 := (Term.UConst 1 t3)
def t5 := (Term.Apply t4 t1)
def t6 := (Term.Apply Term.__eo_List_cons t1)
def t7 := (Term.Apply t6 Term.__eo_List_nil)
def t8 := (Term.Apply (Term.UOp UserOp.forall) t7)
def t9 := (Term.Apply t8 t5)
def t10 := (Term.Apply t4 (Term.Numeral 7))
def t11 := (Term.Apply (Term.UOp UserOp.not) t10)
def t12 := (Term.Apply Term.__eo_List_cons (Term.Numeral 7))
def t13 := (Term.Apply t12 Term.__eo_List_nil)
def t14 := (Term.Apply (Term.UOp UserOp.not) t9)
def t15 := (Term.Apply (Term.UOp UserOp.or) t14)
def t16 := (Term.Apply t15 (Term.Boolean false))
def t17 := (Term.Apply (Term.UOp UserOp.or) t10)
def t18 := (Term.Apply t17 t16)
def t19 := (Term.Apply Term.__eo_List_cons (Term.Boolean false))
def t20 := (Term.Apply t19 Term.__eo_List_nil)
def t21 := (Term.Apply Term.__eo_List_cons (Term.Boolean true))
def t22 := (Term.Apply t21 t20)
def t23 := (Term.Apply Term.__eo_List_cons t9)
def t24 := (Term.Apply t23 Term.__eo_List_nil)
def t25 := (Term.Apply Term.__eo_List_cons t10)
def t26 := (Term.Apply t25 t24)
def s0 : LogosState := logos_init_state
def s1 : LogosState := (logos_invoke_assume s0 t9)
def s2 : LogosState := (logos_invoke_assume s1 t11)
def s3 : LogosState := (logos_invoke_cmd s2 (CCmd.assume_push t9))
def s4 : LogosState := (logos_invoke_cmd s3 (CCmd.step CRule.instantiate (CArgList.cons t13 CArgList.nil) (CIndexList.cons 2 CIndexList.nil)))
def s5 : LogosState := (logos_invoke_cmd s4 (CCmd.step_pop CRule.scope CArgList.nil (CIndexList.cons 0 CIndexList.nil)))
def s6 : LogosState := (logos_invoke_cmd s5 (CCmd.step CRule.process_scope (CArgList.cons t10 CArgList.nil) (CIndexList.cons 0 CIndexList.nil)))
def s7 : LogosState := (logos_invoke_cmd s6 (CCmd.step CRule.implies_elim CArgList.nil (CIndexList.cons 0 CIndexList.nil)))
def s8 : LogosState := (logos_invoke_cmd s7 (CCmd.step CRule.reordering (CArgList.cons t18 CArgList.nil) (CIndexList.cons 0 CIndexList.nil)))
def s9 : LogosState := (logos_invoke_cmd s8 (CCmd.step CRule.chain_m_resolution (CArgList.cons (Term.Boolean false) (CArgList.cons t22 (CArgList.cons t26 CArgList.nil))) (CIndexList.cons 0 (CIndexList.cons 4 (CIndexList.cons 5 CIndexList.nil)))))
#eval!
(logos_state_is_refutation s9)
