-- This file is auto-generated by install/install-cpc.sh, which compiles the
-- Eunoia signature recorded in install/defs/Cpc.cached.eo into Lean.
-- Do not edit. Change the signature, or the compiler, instead.
--
-- The SMT-LIB semantics and the checker specification that these definitions
-- realize are documented in docs/smt-model-definitions.pdf.

module

public import CpcMini.Proofs.CheckerCore
public import CpcMini.Proofs.RuleSupport.Support
import all CpcMini.Logos
import CpcMini.Proofs.Rules.Scope
import CpcMini.Proofs.Rules.Contra
import CpcMini.Proofs.Rules.Refl
import CpcMini.Proofs.Rules.Symm
import CpcMini.Proofs.Rules.Trans


public section

open Eo
open SmtEval
open Smtm

set_option linter.unusedVariables false
set_option maxHeartbeats 10000000


/- Central expansion point for plain `step` rules.

   To add a new rule handled by `__eo_cmd_step_proven`, add its matching
   pattern here and dispatch to the arity helper matching the rule shape.
   The preservation theorems below then pick the new rule up automatically. -/
theorem cmd_step_proven_facts_of_invariants
    (M : SmtModel) (hM : model_wf M)
    (s : CState) (_hNotStuck : s ≠ CState.Stuck)
    (r : CRule) (args : CArgList) (premises : CIndexList) :
  checkerLocalTruthInvariant M s ->
  checkerAssumptionStabilityInvariant M s ->
  checkerTypeInvariant s ->
  checkerTranslationInvariant s ->
  cmdTranslationOk (CCmd.step r args premises) ->
  __eo_typeof (__eo_cmd_step_proven s r args premises) = Term.Bool ->
  CmdStepFacts M s (__eo_cmd_step_proven s r args premises)
:=
by
  intro hs hsStable hsTy hsTrans hCmdTrans hResultTy
  have hProg : __eo_cmd_step_proven s r args premises ≠ Term.Stuck :=
    term_ne_stuck_of_typeof_bool hResultTy
  have hPremisesBool : AllHaveBoolType (premiseTermList s premises) :=
    premiseTermList_has_bool_type s premises hsTy hsTrans
  cases r with
  | contra =>
      exact cmd_step_facts_of_rule_properties M hM s premises hs hsStable <| by
        intro N hN _hAgree
        exact cmd_step_contra_properties N hN s args premises
          (by simpa using hCmdTrans) hPremisesBool hResultTy
  | refl =>
      exact cmd_step_facts_of_rule_properties M hM s premises hs hsStable <| by
        intro N hN _hAgree
        exact cmd_step_refl_properties N hN s args premises
          (by simpa using hCmdTrans) hPremisesBool hResultTy
  | symm =>
      exact cmd_step_facts_of_rule_properties M hM s premises hs hsStable <| by
        intro N hN _hAgree
        exact cmd_step_symm_properties N hN s args premises
          (by simpa using hCmdTrans) hPremisesBool hResultTy
  | trans =>
      exact cmd_step_facts_of_rule_properties M hM s premises hs hsStable <| by
        intro N hN _hAgree
        exact cmd_step_trans_properties N hN s args premises
          (by simpa using hCmdTrans) hPremisesBool hResultTy

  -- Every rule unsupported by plain `step` reduces definitionally to `Stuck`.
  | _ =>
      exact False.elim (hProg rfl)

/-
Central expansion point for `step_pop` rules.

If `__eo_cmd_step_pop_proven` grows more supported rules, add a matching
branch below and route it to the rule-specific helper.
-/
theorem cmd_step_pop_proven_facts_of_invariants
    (M : SmtModel) (hM : model_wf M)
    (root tail : CState) (A : Term)
    (r : CRule) (args : CArgList) (premises : CIndexList) :
  checkerLocalTruthInvariant M root ->
  checkerAssumptionStabilityInvariant M root ->
  checkerTypeInvariant root ->
  checkerTranslationInvariant root ->
  stateStepPopSuffix (CState.cons (CStateObj.assume_push A) tail) root ->
  __eo_typeof (__eo_cmd_step_pop_proven root r args A premises) = Term.Bool ->
  CmdStepFacts M tail (__eo_cmd_step_pop_proven root r args A premises)
:=
by
  intro hsRoot hsRootStable hsRootTy hsRootTrans hSuffix hResultTy
  have hProg : __eo_cmd_step_pop_proven root r args A premises ≠ Term.Stuck :=
    term_ne_stuck_of_typeof_bool hResultTy
  have hsCurTy : checkerTypeInvariant (CState.cons (CStateObj.assume_push A) tail) :=
    checkerTypeInvariant_of_stateStepPopSuffix hSuffix hsRootTy
  have hsCurTrans : checkerTranslationInvariant (CState.cons (CStateObj.assume_push A) tail) :=
    checkerTranslationInvariant_of_stateStepPopSuffix hSuffix hsRootTrans
  have hATy : __eo_typeof A = Term.Bool :=
    (checkerTypeInvariant_head_assume_push A tail hsCurTy).2
  have hATrans : RuleProofs.eo_has_smt_translation A :=
    checkerTranslationInvariant_head_assume_push A tail hsCurTrans
  have hPremisesTrans : AllHaveSmtTranslation (premiseTermList root premises) :=
    premiseTermList_has_smt_translation root premises hsRootTrans
  have hPremisesTy : AllTypeofBool (premiseTermList root premises) :=
    premiseTermList_has_typeof_bool root premises hsRootTy
  cases r with
  | scope =>
      exact cmd_step_pop_facts_of_rule_properties M hM root tail A premises hsRoot hsRootStable hSuffix <|
        cmd_step_pop_scope_properties A root args premises
          hATrans hATy hPremisesTrans hPremisesTy hResultTy

  -- Every rule unsupported by `step_pop` reduces definitionally to `Stuck`.
  | _ =>
      exact False.elim (hProg rfl)
