#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: install/install-smt-std.sh [OPTION]...

Regenerate the Logos Standard SMT-LIB semantics definition in SmtStd/ from
install/defs/smtStd.eo. Install only SmtEval, SmtModelDefs, SmtValueOrder and
SmtModel; discard the compiler's checker, specification and proof artifacts.

Options:
  --check              report whether the four generated files are up to date;
                       leave SmtStd/ untouched
  --ethos PATH         use this Ethos source tree and its build-eoc directory
  --build-dir DIR      override the ethos-eoc build directory
  --deps-dir DIR       where eoc-env.sh is (default: install/deps)
  --semantics PATH     input transformations (default: install/defs/Cpc.eos)
  --smt-semantics PATH SMT semantics (default: the pinned compiler's smt.eos)
  -h, --help           show this message

Run install/get-eo-compiler.sh once to set up the pinned compiler.
After regeneration, build with scripts/build.sh SmtStd.
USAGE
}

expand_tilde() {
  case "$1" in
    "~") printf '%s\n' "${HOME}" ;;
    "~/"*) printf '%s\n' "${HOME}/${1#\~/}" ;;
    *) printf '%s\n' "$1" ;;
  esac
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
CHECK=0
ETHOS_DIR=""
BUILD_DIR=""
DEPS_DIR="${script_dir}/deps"
SEMANTICS="${script_dir}/defs/Cpc.eos"
SMT_SEMANTICS=""

while [ $# -gt 0 ]; do
  case "$1" in
    --check) CHECK=1; shift ;;
    --ethos) ETHOS_DIR="${2:?--ethos requires a value}"; shift 2 ;;
    --ethos=*) ETHOS_DIR="${1#*=}"; shift ;;
    --build-dir) BUILD_DIR="${2:?--build-dir requires a value}"; shift 2 ;;
    --build-dir=*) BUILD_DIR="${1#*=}"; shift ;;
    --deps-dir) DEPS_DIR="${2:?--deps-dir requires a value}"; shift 2 ;;
    --deps-dir=*) DEPS_DIR="${1#*=}"; shift ;;
    --semantics) SEMANTICS="${2:?--semantics requires a value}"; shift 2 ;;
    --semantics=*) SEMANTICS="${1#*=}"; shift ;;
    --smt-semantics) SMT_SEMANTICS="${2:?--smt-semantics requires a value}"; shift 2 ;;
    --smt-semantics=*) SMT_SEMANTICS="${1#*=}"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unrecognized option $1" >&2; usage >&2; exit 1 ;;
  esac
done

ETHOS_DIR="$(expand_tilde "${ETHOS_DIR}")"
BUILD_DIR="$(expand_tilde "${BUILD_DIR}")"
DEPS_DIR="$(expand_tilde "${DEPS_DIR}")"
SEMANTICS="$(expand_tilde "${SEMANTICS}")"
SMT_SEMANTICS="$(expand_tilde "${SMT_SEMANTICS}")"

if [ -f "${DEPS_DIR}/eoc-env.sh" ]; then
  # shellcheck source=/dev/null
  source "${DEPS_DIR}/eoc-env.sh"
fi
# A named checkout must not use a build configured against the recorded tree:
# the binary resolves its templates against the checkout it was built from.
if [ -n "${ETHOS_DIR}" ]; then
  BUILD_DIR="${BUILD_DIR:-${ETHOS_DIR}/build-eoc}"
else
  ETHOS_DIR="${EOC_ETHOS_DIR:-${DEPS_DIR}/ethos}"
  BUILD_DIR="${BUILD_DIR:-${EOC_BUILD_DIR:-${ETHOS_DIR}/build-eoc}}"
fi
DRIVER="${ETHOS_DIR}/tools/eoc/driver.py"
if [ ! -f "${DRIVER}" ]; then
  echo "error: ${DRIVER} not found. Run install/get-eo-compiler.sh first," >&2
  echo "or name a compiler checkout with --ethos." >&2
  exit 1
fi

# Always compile afresh in a disposable directory, so stale output cannot be
# mistaken for a successful compilation. Validate every module before writing.
stage="$(mktemp -d "${TMPDIR:-/tmp}/install-smt-std.XXXXXX")"
trap 'rm -rf "${stage}"' EXIT
driver_args=(lean --all "${script_dir}/defs/smtStd.eo"
  --calc-name SmtStd --no-parser --skip-cvc5
  --build-dir "${BUILD_DIR}" --final-out-dir "${stage}"
  --semantics "${SEMANTICS}")
[ -z "${SMT_SEMANTICS}" ] || driver_args+=(--smt-semantics "${SMT_SEMANTICS}")
[ ! -x "${BUILD_DIR}/ethos-eoc" ] || driver_args+=(--no-build)
python3 "${DRIVER}" "${driver_args[@]}"

modules=(SmtEval SmtModelDefs SmtValueOrder SmtModel)
for name in "${modules[@]}"; do
  if [ ! -s "${stage}/lean/${name}.lean" ]; then
    echo "error: the compiler did not produce ${name}.lean; nothing installed." >&2
    exit 1
  fi
done

# The compiler shares the names SmtEval and Smtm across calculi. Qualify this
# standalone library's declarations so clients can also import Cpc.
python3 - "${stage}/lean" <<'PY'
from pathlib import Path
import re
import sys

header = """-- Logos Standard SMT-LIB semantics definition.
-- Auto-generated by install/install-smt-std.sh from install/defs/smtStd.eo,
-- install/defs/Cpc.eos and the pinned Eunoia compiler's SMT semantics.
-- Do not edit; regenerate from those sources instead.
-- See install/README.md for the relationship to Cpc and coverage limits.

"""
for name in ("SmtEval", "SmtModelDefs", "SmtValueOrder", "SmtModel"):
    path = Path(sys.argv[1]) / f"{name}.lean"
    source = re.sub(r"^(namespace|end) (SmtEval|Smtm)$", r"\1 SmtStd.\2",
                    path.read_text(), flags=re.MULTILINE)
    path.write_text(header + source)
PY

dest="${repo_root}/SmtStd"
changed=0
for name in "${modules[@]}"; do
  if ! cmp -s "${stage}/lean/${name}.lean" "${dest}/${name}.lean"; then
    changed=1
    if [ "${CHECK}" = "1" ]; then
      echo "out of date: SmtStd/${name}.lean"
    else
      mkdir -p "${dest}"
      cp "${stage}/lean/${name}.lean" "${dest}/${name}.lean"
      echo "installed: SmtStd/${name}.lean"
    fi
  fi
done
if [ "${CHECK}" = "1" ] && [ "${changed}" = "1" ]; then
  echo "SmtStd is out of date. Run install/install-smt-std.sh to regenerate it."
  exit 1
fi
echo "SmtStd is up to date with install/defs/smtStd.eo."
